COMPASS-213: Pass readonly options to collections
mongodb-js/instance-model pull request #106
Opened 2016-11-10 19:45 UTC by durran

2016-11-10 21:24 UTC, imlucas requested changes

2016-11-10 21:24 UTC, imlucas commented on lib/fetch.js
> +    readonly: resp.info ? resp.info.readOnly : false
`_.get(resp, 'info.readOnly', false)`

2016-11-10 21:24 UTC, imlucas commented on test/fetch-mocked.test.js
> +            'readOnly': true
Shouldn't this be `'readonly': true`?

2016-11-11 09:10 UTC, durran reviewed
Changes made and collection model bumped.

2016-11-11 15:08 UTC, aherlihy commented
LGTM

2016-11-11 15:09 UTC, merged